// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDzOk2pWclwkV4xbYJ_IIBQ75DREYEhd0',
    appId: '1:304681361245:web:80de888177d2354a79d2b4',
    messagingSenderId: '304681361245',
    projectId: 'foodapp-1d0ce',
    authDomain: 'foodapp-1d0ce.firebaseapp.com',
    storageBucket: 'foodapp-1d0ce.appspot.com',
    measurementId: 'G-70E5W9H6FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkNIaJNI6fFQv2-OiwSaTNJrht_xbo68Q',
    appId: '1:304681361245:android:a63789e51f5e5b9079d2b4',
    messagingSenderId: '304681361245',
    projectId: 'foodapp-1d0ce',
    storageBucket: 'foodapp-1d0ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlCcAEQgb8SdqtN06fSspPE0wlN6ezUXU',
    appId: '1:304681361245:ios:f2b70d9e7f864e6579d2b4',
    messagingSenderId: '304681361245',
    projectId: 'foodapp-1d0ce',
    storageBucket: 'foodapp-1d0ce.appspot.com',
    iosBundleId: 'com.example.foodappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlCcAEQgb8SdqtN06fSspPE0wlN6ezUXU',
    appId: '1:304681361245:ios:fb30803c98ef65cc79d2b4',
    messagingSenderId: '304681361245',
    projectId: 'foodapp-1d0ce',
    storageBucket: 'foodapp-1d0ce.appspot.com',
    iosBundleId: 'com.example.foodappFlutter.RunnerTests',
  );
}
